[project]
name = "prune-openapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "typer>=0.12,<0.15",
]

[project.scripts]
prune-openapi = "main:app"
